stages:
  - prepare
  - build

image: golang:1.22-alpine

vet:
  stage: prepare
  script:
    - go mod download
    - go vet

unit-test:
  stage: prepare
  script:
    - go test

build:
  stage: build
  needs:
    - vet
    - unit-test
  dependencies:
    - vet
    - unit-test
  script:
    - go build

