version: "3.8"
x-stack:
  name: zuck-my-clothe-stack
services:
  zuck-my-clothe-go-backend:
    container_name: zuck-my-cloth-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:3000
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 19997:5432
    volumes:
      - ~/cpe334/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=F6maCUmIavQKWAq
      - POSTGRES_USER=root
      - POSTGRES_DB=zuck-my-clothe
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8003:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zuck-my-clothe.com
      PGADMIN_DEFAULT_PASSWORD: F6maCUmIavQKWAq
    volumes:
      - ~/cpe334/pgadmin:/var/lib/pgadmin
